name: Docker Image CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - name: "Build:checkout"
        uses: actions/checkout@v2
      - name: 'Build:dockerimage'
        uses: docker/build-push-action@v1
        with:
          registry: ghcr.io
          username: "bezha"
          password: ${{ secrets.CR_PAT }}
          repository: bezha/docker_megacli_on_ghcr.io
          tags: latest
